[colors.primary]
background = '{{colors.background.default.hex}}'
foreground = '{{colors.on_surface.default.hex}}'

[colors.selection]
text = '{{colors.on_surface.default.hex}}'
background = '{{colors.primary_container.default.hex}}'

[colors.cursor]
text = '{{colors.background.default.hex}}'
cursor = '{{colors.primary.default.hex}}'

[colors.normal]
black   = '{{dank16.color0.hex}}'
red     = '{{dank16.color1.hex}}'
green   = '{{dank16.color2.hex}}'
yellow  = '{{dank16.color3.hex}}'
blue    = '{{dank16.color4.hex}}'
magenta = '{{dank16.color5.hex}}'
cyan    = '{{dank16.color6.hex}}'
white   = '{{dank16.color7.hex}}'

[colors.bright]
black   = '{{dank16.color8.hex}}'
red     = '{{dank16.color9.hex}}'
green   = '{{dank16.color10.hex}}'
yellow  = '{{dank16.color11.hex}}'
blue    = '{{dank16.color12.hex}}'
magenta = '{{dank16.color13.hex}}'
cyan    = '{{dank16.color14.hex}}'
white   = '{{dank16.color15.hex}}'
